# This file was generated by GoReleaser. DO NOT EDIT.
cask "vox-actor" do
  version "0.0.10"

  on_macos do
    on_intel do
      sha256 "3fcc05c310a42a023c4ebe74e2648d603eee9809944ee9966104df07713e1a35"
      url "https://github.com/canpok1/vox-actor/releases/download/v#{version}/vox-actor_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "fcd984eb71a3c0d2df71b4215c019414e170c473eb55241430c7b289071f3a9a"
      url "https://github.com/canpok1/vox-actor/releases/download/v#{version}/vox-actor_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "31cfd3ee2f04d6092e346513192958b4ab1b00ad922cbe32ffc6c99290794683"
      url "https://github.com/canpok1/vox-actor/releases/download/v#{version}/vox-actor_Linux_x86_64.tar.gz"
    end
  end

  name "vox-actor"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vox-actor"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/vox-actor"]
    end
  end

  # No zap stanza required

end
