# This file was generated by GoReleaser. DO NOT EDIT.
cask "vox-actor" do
  version "0.0.15"

  on_macos do
    on_intel do
      sha256 "62dbc7142753d42379ae0ab5c675851eadd3dd3f2c149dd0c5cf3b77b4247d4b"
      url "https://github.com/canpok1/vox-actor/releases/download/v#{version}/vox-actor_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "9a068b0c987ea87ad0a8f380b86886dbe3b06ad54ee34db8cddfb1c33c3a3b9a"
      url "https://github.com/canpok1/vox-actor/releases/download/v#{version}/vox-actor_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8cae7baf6a17600b9e77990d3f9f05dc155513def1f2efdfff71338a2d7fcf17"
      url "https://github.com/canpok1/vox-actor/releases/download/v#{version}/vox-actor_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "a30290eba17baef63dbc8ae013514bda0b13b5dc2ebab22dd2ad53d7b8a4caeb"
      url "https://github.com/canpok1/vox-actor/releases/download/v#{version}/vox-actor_Linux_arm64.tar.gz"
    end
  end

  name "vox-actor"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vox-actor"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/vox-actor"]
    end
  end

  # No zap stanza required

end
