# This file was generated by GoReleaser. DO NOT EDIT.
cask "vox-actor" do
  version "0.0.12"

  on_macos do
    on_intel do
      sha256 "4048450996bea5814abafb4ed357657adf1b694f39d21b3522c46b4fe2c1f218"
      url "https://github.com/canpok1/vox-actor/releases/download/v#{version}/vox-actor_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "d6e20942a4bdc50666fc15980c49ba86918d7a0d6475a70f8fe7b1b640771ad4"
      url "https://github.com/canpok1/vox-actor/releases/download/v#{version}/vox-actor_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7f86b5df149d8b15f8c03f1f19a3e584180c7cb4472c4e04455e3677f8ddb456"
      url "https://github.com/canpok1/vox-actor/releases/download/v#{version}/vox-actor_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "f1ab0a7d1aaebe1e35883179e81e219cad8d26d468fbf28d2e5be8a374c423bd"
      url "https://github.com/canpok1/vox-actor/releases/download/v#{version}/vox-actor_Linux_arm64.tar.gz"
    end
  end

  name "vox-actor"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vox-actor"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/vox-actor"]
    end
  end

  # No zap stanza required

end
