# This file was generated by GoReleaser. DO NOT EDIT.
cask "vox-radio" do
  version "1.0.3"

  on_macos do
    on_intel do
      sha256 "038c701eb818fccbc439487666fac0dadae6b576d3c3e92b8a410f71419396b1"
      url "https://github.com/canpok1/vox-radio/releases/download/v#{version}/vox-radio_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "4f26dfe6f9e0f1d5b3cd44f4448973da21d1e9376bfac579d6254892ad232b0c"
      url "https://github.com/canpok1/vox-radio/releases/download/v#{version}/vox-radio_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "01c2524cd2c25b0c259529a8202ac33bfff42d41c299bc26051778f8ca1843a1"
      url "https://github.com/canpok1/vox-radio/releases/download/v#{version}/vox-radio_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "831f3392f27e45a199e3a2e9a47c51e24b7a3f57a87198d5902964bd89e44ce4"
      url "https://github.com/canpok1/vox-radio/releases/download/v#{version}/vox-radio_Linux_arm64.tar.gz"
    end
  end

  name "vox-radio"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "ffmpeg",
    ]

  binary "vox-radio"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/vox-radio"]
    end
  end

  # No zap stanza required

end
