# This file was generated by GoReleaser. DO NOT EDIT.
cask "vox-radio" do
  version "1.0.1"

  on_macos do
    on_intel do
      sha256 "0db7c311a1ac8c8f62cca213b2e51e73514a463d148d7ff522f2ba4adcd42426"
      url "https://github.com/canpok1/vox-radio/releases/download/v#{version}/vox-radio_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "562a7aaf9693a953db32762a9456e6f25233cc6b843509e0aceb18cf90e26142"
      url "https://github.com/canpok1/vox-radio/releases/download/v#{version}/vox-radio_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "bfac843fc2e69191610afcdca90d3d300ec655f93eee8ed5bf09ebfae4eb160f"
      url "https://github.com/canpok1/vox-radio/releases/download/v#{version}/vox-radio_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "d0d39b8f6212a6704aadfbdab83b71a86c2fc1473cdbcc77b9cec6750f8f2501"
      url "https://github.com/canpok1/vox-radio/releases/download/v#{version}/vox-radio_Linux_arm64.tar.gz"
    end
  end

  name "vox-radio"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "ffmpeg",
    ]

  binary "vox-radio"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/vox-radio"]
    end
  end

  # No zap stanza required

end
