# This file was generated by GoReleaser. DO NOT EDIT.
cask "vox-radio" do
  version "1.0.4"

  on_macos do
    on_intel do
      sha256 "daa2f6f0ccc5441d24a94630c742444faa5147929fae98e1d7d29b167bf0d237"
      url "https://github.com/canpok1/vox-radio/releases/download/v#{version}/vox-radio_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "66e499b92877dc4bae88c6ecee26dbb8f4a8c6c666bf1e8e857e3ec09eb94cb6"
      url "https://github.com/canpok1/vox-radio/releases/download/v#{version}/vox-radio_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c54457db10010e1edd805c83918413dae6226a7467477fbce55a24a6d30c9644"
      url "https://github.com/canpok1/vox-radio/releases/download/v#{version}/vox-radio_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "afdc823c7836f4d1551f4ce4555da960e3c80aa8fd23a189b6530eacf0c4988c"
      url "https://github.com/canpok1/vox-radio/releases/download/v#{version}/vox-radio_Linux_arm64.tar.gz"
    end
  end

  name "vox-radio"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "ffmpeg",
    ]

  binary "vox-radio"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/vox-radio"]
    end
  end

  # No zap stanza required

end
